"""Deterministic script exporters for TaskSpec execution.

The exporter provides a safe product-facing meaning of "script generation": it
writes thin, auditable wrapper code that executes an already validated TaskSpec
through the trusted sat_sim pipeline. It does not ask an LLM to write arbitrary
Python.
"""
from __future__ import annotations
from utils.runtime_diagnostics import DiagnosticCategory, record_runtime_diagnostic

import json
import pprint
import shlex
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Literal, Mapping


ScriptKind = Literal["python", "shell", "capability-python", "assembly-python"]


@dataclass(frozen=True)
class ScriptExportResult:
    kind: ScriptKind
    output_path: Path
    spec_path: Path
    output_root: str | None = None

    def to_dict(self) -> dict[str, str | None]:
        payload = asdict(self)
        payload["output_path"] = str(self.output_path)
        payload["spec_path"] = str(self.spec_path)
        return payload


def _quote_python_path(path: Path) -> str:
    return repr(str(path))


def export_python_runner(spec_path: str | Path, output_path: str | Path, *, output_root: str | Path | None = None) -> ScriptExportResult:
    spec = Path(spec_path)
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    output_root_expr = repr(str(output_root)) if output_root is not None else "None"
    content = f'''#!/usr/bin/env python3
"""Generated TaskSpec runner.

This file is deterministic wrapper code generated by sat_sim.script_exporter.
Edit the TaskSpec YAML/JSON, not this wrapper, when changing simulation physics
or scenario parameters.
"""

import json
from pathlib import Path

from sat_sim.task_spec import load_task_spec
from sat_sim.task_validator import validate_task_spec
from sat_sim.task_compiler import compile_task_spec
from sat_sim.unified_execution import execute_compiled_task

SPEC_PATH = Path({_quote_python_path(spec)})
OUTPUT_ROOT = {output_root_expr}


def main() -> int:
    doc = load_task_spec(SPEC_PATH)
    validation = validate_task_spec(doc.data)
    validation.raise_for_errors()
    compiled = compile_task_spec(doc.data, validate=False)
    result = execute_compiled_task(compiled, task_spec=doc.data, output_root=OUTPUT_ROOT or compiled.outputs.get("output_root"), write_dataset=True)
    print(json.dumps({{"ok": True, "task_id": compiled.task_id, "summary": result.summary, "dataset": result.dataset.to_dict() if result.dataset else None}}, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''
    out.write_text(content, encoding="utf-8")
    try:
        out.chmod(out.stat().st_mode | 0o111)
    except Exception as exc:
        record_runtime_diagnostic(
            code='SCRIPT_EXECUTABLE_PERMISSION_UPDATE_FAILED',
            category=DiagnosticCategory.BEST_EFFORT_CLEANUP,
            location='src/sat_sim/script_exporter.py:export_python_runner:01',
            exception=exc,
            strict=False,
        )
    return ScriptExportResult(kind="python", output_path=out, spec_path=spec, output_root=str(output_root) if output_root is not None else None)


def export_shell_runner(spec_path: str | Path, output_path: str | Path, *, output_root: str | Path | None = None) -> ScriptExportResult:
    spec = Path(spec_path)
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    cmd = ["sat-sim", "run", str(spec)]
    if output_root is not None:
        cmd += ["--output", str(output_root)]
    content = "#!/usr/bin/env bash\nset -euo pipefail\n" + " ".join(shlex.quote(part) for part in cmd) + "\n"
    out.write_text(content, encoding="utf-8")
    try:
        out.chmod(out.stat().st_mode | 0o111)
    except Exception as exc:
        record_runtime_diagnostic(
            code='SCRIPT_EXECUTABLE_PERMISSION_UPDATE_FAILED',
            category=DiagnosticCategory.BEST_EFFORT_CLEANUP,
            location='src/sat_sim/script_exporter.py:export_shell_runner:01',
            exception=exc,
            strict=False,
        )
    return ScriptExportResult(kind="shell", output_path=out, spec_path=spec, output_root=str(output_root) if output_root is not None else None)


def _source_binding_comment(source_binding: Mapping[str, Any]) -> str:
    mode = source_binding.get("mode", "unknown")
    primary = source_binding.get("primary_module", "")
    public_api = source_binding.get("public_api") or []
    if isinstance(public_api, list):
        public_api_text = ", ".join(str(x) for x in public_api[:8])
    else:
        public_api_text = str(public_api)
    return f"# Source binding: mode={mode}; primary_module={primary}; public_api={public_api_text}"


def _generate_capability_python_script(
    payload: Mapping[str, Any],
    contract_data: Mapping[str, Any],
    *,
    assembly_graph: Mapping[str, Any] | None = None,
) -> str:
    from .source_native import public_source_binding_payload

    capability_id = str(contract_data.get("capability_id", payload.get("capability_id", "")))
    source_binding = public_source_binding_payload(contract_data)
    task_spec_literal = pprint.pformat(dict(payload), width=100, sort_dicts=False)
    source_binding_literal = pprint.pformat(dict(source_binding), width=100, sort_dicts=False)
    source_comment = _source_binding_comment(source_binding)
    assembly_literal = pprint.pformat(dict(assembly_graph), width=100, sort_dicts=False) if assembly_graph is not None else "None"
    assembly_import = (
        "from sat_sim.assembly_graph import validate_assembly_graph, validate_assembly_task_spec_binding\n"
        if assembly_graph is not None else ""
    )
    assembly_validation = (
        "    assembly_validation = validate_assembly_graph(ASSEMBLY_GRAPH, expected_parent_capability_id=CAPABILITY_ID)\n"
        "    if not assembly_validation.ok:\n"
        "        raise SystemExit(json.dumps({\"ok\": False, \"assembly_validation\": assembly_validation.to_dict()}, indent=2, ensure_ascii=False))\n"
        if assembly_graph is not None else ""
    )
    assembly_task_binding = (
        "    assembly_task_binding = validate_assembly_task_spec_binding(task_spec, ASSEMBLY_GRAPH, validation=assembly_validation)\n"
        "    if not assembly_task_binding.get(\"ok\"):\n"
        "        raise SystemExit(json.dumps({\"ok\": False, \"assembly_task_binding\": assembly_task_binding}, indent=2, ensure_ascii=False))\n"
        if assembly_graph is not None else ""
    )
    default_output = str((payload.get("outputs") if isinstance(payload.get("outputs"), Mapping) else {}).get("output_root") or payload.get("task_id") or "capability_output")
    return f'''#!/usr/bin/env python3
"""Generated capability-python simulation script.

This script is deterministic code generated by sat_sim.script_exporter.  It uses
the same unified execution path as product TaskSpec runs; it is not authored by
an LLM and does not import capability adapter class paths directly.
"""

import argparse
import copy
import json
from typing import Any

from sat_sim.task_compiler import compile_task_spec
from sat_sim.taskspec_alignment import align_task_spec_to_source
from sat_sim.unified_execution import execute_compiled_task
{assembly_import}
CAPABILITY_ID = {capability_id!r}
SOURCE_BINDING = {source_binding_literal}
ASSEMBLY_GRAPH = {assembly_literal}
{source_comment}

# ---------------------------------------------------------------------------
# User-editable TaskSpec parameter section
# ---------------------------------------------------------------------------
# Edit TASK_SPEC values directly, or override them at runtime with:
#   --duration-s 3600 --sample-s 30 --output-root datasets/my_run
#   --set parameters.capacity_bits=8000000 --set parameters.generated_bps=2000
#
# Scenario modifiers live under TASK_SPEC["modifiers"]. They are not standalone
# runnable capabilities. Example:
#   modifiers.faults=[{{"target":"eps.battery","fault_type":"capacity_drop","onset_time_s":120,"severity":0.2}}]
TASK_SPEC = {task_spec_literal}


# ---------------------------------------------------------------------------
# Runtime helpers
# ---------------------------------------------------------------------------
def _parse_value(text: str) -> Any:
    try:
        return json.loads(text)
    except Exception:
        return text


def _set_path(data: dict[str, Any], dotted_path: str, value: Any) -> None:
    cur = data
    parts = dotted_path.split(".")
    for part in parts[:-1]:
        nxt = cur.get(part)
        if not isinstance(nxt, dict):
            nxt = {{}}
            cur[part] = nxt
        cur = nxt
    cur[parts[-1]] = value


def build_task_spec(args: argparse.Namespace) -> dict[str, Any]:
    spec = copy.deepcopy(TASK_SPEC)
    if args.duration_s is not None:
        _set_path(spec, "simulation.duration_s", float(args.duration_s))
    if args.sample_s is not None:
        _set_path(spec, "simulation.sample_s", float(args.sample_s))
    if args.output_root is not None:
        _set_path(spec, "outputs.output_root", str(args.output_root))
    for item in args.set or []:
        if "=" not in item:
            raise SystemExit(f"--set expects dotted.path=value, got {{item!r}}")
        path, raw = item.split("=", 1)
        if not path.strip():
            raise SystemExit(f"--set path cannot be empty: {{item!r}}")
        _set_path(spec, path.strip(), _parse_value(raw))
    return align_task_spec_to_source(spec, fill_defaults=True).task_spec


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=f"Run {{CAPABILITY_ID}} capability simulation.")
    parser.add_argument("--output-root", default={default_output!r}, help="dataset output directory")
    parser.add_argument("--duration-s", type=float, help="override simulation.duration_s")
    parser.add_argument("--sample-s", type=float, help="override simulation.sample_s")
    parser.add_argument("--set", action="append", default=[], metavar="PATH=VALUE", help="override any TaskSpec dotted path; VALUE is parsed as JSON when possible")
    parser.add_argument("--show-task-spec", action="store_true", help="print normalized TaskSpec before running")
    return parser.parse_args()


def main() -> int:
{assembly_validation}    args = parse_args()
    task_spec = build_task_spec(args)
{assembly_task_binding}    if args.show_task_spec:
        print(json.dumps(task_spec, indent=2, ensure_ascii=False))
    compiled = compile_task_spec(task_spec, validate=True)
    output_root = task_spec.get("outputs", {{}}).get("output_root") or args.output_root or {default_output!r}
    result = execute_compiled_task(
        compiled,
        task_spec=task_spec,
        output_root=output_root,
        write_dataset=True,
    )
    status = str(result.summary.get("status") or "complete").strip().lower()
    failed_statuses = {{"fail", "failed", "error", "inconclusive", "blocked"}}
    ok = status not in failed_statuses and not status.startswith("fail")
    payload = {{
        "ok": ok,
        "capability_id": CAPABILITY_ID,
        "summary": result.summary,
        "dataset": result.dataset.to_dict() if result.dataset else None,
    }}
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    return 0 if payload["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''


def export_capability_python_runner(spec_path: str | Path, output_path: str | Path, *, output_root: str | Path | None = None) -> ScriptExportResult:
    """Export readable adapter-backed Python code for a capability TaskSpec.

    This path still requires ``capability_id`` and still executes the explicit
    capability adapter. S6 centralizes the wrapper template so every exported
    script has the same parameter block, argparse overrides, and source-binding
    comments.
    """

    from .capability_registry import get_capability
    from .task_spec import load_task_spec
    from .task_models import to_runtime_task_spec
    from .taskspec_alignment import align_task_spec_to_source

    spec = Path(spec_path)
    out = Path(output_path)
    doc = load_task_spec(spec)
    payload = to_runtime_task_spec(doc.data)
    capability_id = payload.get("capability_id")
    if not isinstance(capability_id, str) or not capability_id.strip():
        raise ValueError("capability-python export requires TaskSpec capability_id")
    contract = get_capability(capability_id)
    payload = dict(payload)
    if output_root is not None:
        outputs = dict(payload.get("outputs") or {})
        outputs["output_root"] = str(output_root)
        payload["outputs"] = outputs
    payload = align_task_spec_to_source(payload, capability=contract.data, fill_defaults=True).task_spec
    try:
        from .taskspec_pruning import prune_task_spec_for_capability
        payload = prune_task_spec_for_capability(payload).task_spec
    except Exception as exc:
        record_runtime_diagnostic(
            code='SCRIPT_EXPORT_PRUNING_FALLBACK',
            category=DiagnosticCategory.AGENT_NORMALIZATION_FALLBACK,
            location='src/sat_sim/script_exporter.py:export_capability_python_runner:01',
            exception=exc,
            strict=False,
        )
    content = _generate_capability_python_script(payload, contract.data)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    try:
        out.chmod(out.stat().st_mode | 0o111)
    except Exception as exc:
        record_runtime_diagnostic(
            code='SCRIPT_EXECUTABLE_PERMISSION_UPDATE_FAILED',
            category=DiagnosticCategory.BEST_EFFORT_CLEANUP,
            location='src/sat_sim/script_exporter.py:export_capability_python_runner:02',
            exception=exc,
            strict=False,
        )
    return ScriptExportResult(kind="capability-python", output_path=out, spec_path=spec, output_root=str(output_root) if output_root is not None else None)


def export_assembly_python_runner(
    spec_path: str | Path,
    output_path: str | Path,
    *,
    assembly_graph: Mapping[str, Any],
    output_root: str | Path | None = None,
) -> ScriptExportResult:
    """Export deterministic executable code with a registered module assembly.

    The assembly is embedded as data and revalidated at runtime.  Execution is
    still owned by the registered parent Capability adapter; no arbitrary class
    path or Python source is accepted from the graph.
    """
    from .assembly_graph import validate_assembly_graph, validate_assembly_task_spec_binding
    from .capability_registry import get_capability
    from .task_spec import load_task_spec
    from .task_models import to_runtime_task_spec
    from .taskspec_alignment import align_task_spec_to_source

    spec = Path(spec_path)
    out = Path(output_path)
    doc = load_task_spec(spec)
    payload = to_runtime_task_spec(doc.data)
    capability_id = payload.get("capability_id")
    if not isinstance(capability_id, str) or not capability_id.strip():
        raise ValueError("assembly-python export requires TaskSpec capability_id")
    assembly_validation = validate_assembly_graph(
        assembly_graph,
        expected_parent_capability_id=capability_id,
        require_all_bindings=True,
    )
    if not assembly_validation.ok:
        messages = "; ".join(item.message for item in assembly_validation.errors[:8])
        raise ValueError(f"assembly graph validation failed: {messages}")
    assembly_task_binding = validate_assembly_task_spec_binding(
        doc.data,
        assembly_graph,
        validation=assembly_validation,
    )
    if not assembly_task_binding.get("ok"):
        messages = "; ".join(str(item.get("message") or item.get("code")) for item in assembly_task_binding.get("errors", [])[:8])
        raise ValueError(f"assembly TaskSpec binding validation failed: {messages}")
    contract = get_capability(capability_id)
    payload = dict(payload)
    if output_root is not None:
        outputs = dict(payload.get("outputs") or {})
        outputs["output_root"] = str(output_root)
        payload["outputs"] = outputs
    payload = align_task_spec_to_source(payload, capability=contract.data, fill_defaults=True).task_spec
    try:
        from .taskspec_pruning import prune_task_spec_for_capability
        payload = prune_task_spec_for_capability(payload).task_spec
    except Exception as exc:
        record_runtime_diagnostic(
            code="ASSEMBLY_SCRIPT_EXPORT_PRUNING_FALLBACK",
            category=DiagnosticCategory.AGENT_NORMALIZATION_FALLBACK,
            location="src/sat_sim/script_exporter.py:export_assembly_python_runner:01",
            exception=exc,
            strict=False,
        )
    # Visual observer annotations (for example Scope probes) are project/UI data,
    # not part of the physical assembly runtime.  Validate the submitted graph
    # above, but deliberately omit observers from the generated runner so adding
    # or moving a Scope cannot change executable simulation code.
    runtime_assembly_graph = dict(assembly_graph)
    runtime_assembly_graph.pop("scopes", None)
    content = _generate_capability_python_script(payload, contract.data, assembly_graph=runtime_assembly_graph)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    try:
        out.chmod(out.stat().st_mode | 0o111)
    except Exception as exc:
        record_runtime_diagnostic(
            code="SCRIPT_EXECUTABLE_PERMISSION_UPDATE_FAILED",
            category=DiagnosticCategory.BEST_EFFORT_CLEANUP,
            location="src/sat_sim/script_exporter.py:export_assembly_python_runner:02",
            exception=exc,
            strict=False,
        )
    return ScriptExportResult(kind="assembly-python", output_path=out, spec_path=spec, output_root=str(output_root) if output_root is not None else None)


def export_runner_script(spec_path: str | Path, output_path: str | Path, *, kind: ScriptKind = "python", output_root: str | Path | None = None) -> ScriptExportResult:
    if kind == "python":
        return export_python_runner(spec_path, output_path, output_root=output_root)
    if kind == "shell":
        return export_shell_runner(spec_path, output_path, output_root=output_root)
    if kind == "capability-python":
        return export_capability_python_runner(spec_path, output_path, output_root=output_root)
    if kind == "assembly-python":
        raise ValueError("assembly-python export requires export_assembly_python_runner(..., assembly_graph=...)")
    raise ValueError(f"unsupported script kind: {kind!r}")


__all__ = [
    "ScriptExportResult",
    "ScriptKind",
    "export_python_runner",
    "export_shell_runner",
    "export_capability_python_runner",
    "export_assembly_python_runner",
    "export_runner_script",
]
