"""v8.23 normal/boundary campaign for the selective unified Basilisk assembly.

This campaign runs a small, explicit set of normal and normal-boundary cases on
``validation.legacy.whole_spacecraft.selective_unified_assembly``.  It is intended for dataset
collection and quality checks, not for fault injection or formal acceptance.

Truthfulness boundary:
* All traces are generated by the v8.22 selective unified Basilisk assembly path
  through ``SimulationBaseClass.ExecuteSimulation()``.
* Thermal remains a Basilisk-scheduled custom SysModel, not a native Basilisk
  all-spacecraft thermal network.
* Boundary cases are normal-boundary labels with ``fault_type = none`` and
  ``is_fault = false``.
"""
from __future__ import annotations

import csv
import json
import math
from dataclasses import asdict, dataclass, replace
from pathlib import Path
from typing import Iterable

# v8.25.1 long-horizon normal-boundary defaults.
# The original v8.25 campaign used 180 s traces, which was useful for smoke
# testing but too short to serve as a satellite normal-boundary baseline for
# v9 fault-injection acceptance.  Keep the selective unified Basilisk path,
# but run a 6 h horizon with coarser sampling and stable 10 s dynamics/FSW
# tasks.
LONG_BOUNDARY_DURATION_S = 6.0 * 3600.0
LONG_BOUNDARY_DYN_STEP_S = 10.0
LONG_BOUNDARY_FSW_STEP_S = 10.0
LONG_BOUNDARY_POWER_STEP_S = 60.0
LONG_BOUNDARY_SAMPLE_S = 60.0
MIN_LONG_BOUNDARY_DURATION_S = 6.0 * 3600.0

from .selective_unified_assembly import (
    SelectiveUnifiedAssemblyConfig,
    SelectiveUnifiedAssemblyTraceRow,
    run_selective_unified_assembly,
)


@dataclass(frozen=True)
class CampaignScenario:
    scenario_id: str
    name: str
    scenario_type: str  # normal | normal_boundary
    mode: str
    boundary_type: str
    expected_active_subsystems: tuple[str, ...]
    expected_blocked_subsystems: tuple[str, ...]
    config: SelectiveUnifiedAssemblyConfig
    event_rule: str


@dataclass(frozen=True)
class ScenarioQoISummary:
    scenario_id: str
    name: str
    scenario_type: str
    status: str
    sample_count: int
    final_soc: float
    min_soc: float
    final_data_storage_bits: float
    max_data_storage_bits: float
    min_thermal_margin_c: float
    max_attitude_error_ratio: float
    final_attitude_error_ratio: float
    propellant_used_kg: float
    max_velocity_x_m_s: float
    boundary_event_count: int
    warning_count: int
    fail_count: int


@dataclass(frozen=True)
class ScenarioLabel:
    scenario_id: str
    scenario_name: str
    scenario_type: str
    fault_type: str
    boundary_type: str
    expected_active_subsystems: str
    expected_blocked_subsystems: str
    is_fault: bool


@dataclass(frozen=True)
class BoundaryEventLabel:
    scenario_id: str
    time_s: float
    event_type: str
    severity: str
    source_subsystem: str
    description: str
    is_fault: bool


UNIFIED_TRACE_FIELDS = (
    "scenario_id", "scenario_name", "scenario_type", "mode", "time_s",
    "soc", "battery_storage_j", "solar_power_w", "bus_load_w",
    "payload_load_enabled_w", "adcs_load_enabled_w", "comm_load_enabled_w", "heater_load_enabled_w",
    "load_shed_active", "shed_reason", "payload_enabled", "payload_block_reason",
    "data_storage_bits", "generated_bits", "downlinked_bits", "ground_access", "link_rate_bps",
    "thermal_temp_c", "thermal_safe", "heater_enabled", "cooling_enabled", "thermal_margin_c",
    "attitude_error_norm", "attitude_error_ratio", "rw_speed_0_rad_s", "rw_speed_1_rad_s", "rw_speed_2_rad_s",
    "rw_speed_sum_nms",  # v8.25.2: renamed from rw_speed_sum_proxy for clarity
    "rw_motor_torque_command_0_nm", "rw_motor_torque_command_1_nm", "rw_motor_torque_command_2_nm",  # NOTE: command, not measured
    "rw_motor_torque_command_norm_nm",  # NOTE: command norm, not measured
    "sensor_quality_flag", "nav_innovation_norm",  # v8.25.2: moved from legacy rw_motor_torque_proxy line
    "thruster_on", "thruster_on_time_s", "fuel_mass_kg", "propellant_used_kg", "delta_v_proxy",
)


def _scenario_configs(
    duration_s: float = LONG_BOUNDARY_DURATION_S,
    sample_s: float = LONG_BOUNDARY_SAMPLE_S,
    dyn_step_s: float = LONG_BOUNDARY_DYN_STEP_S,
    fsw_step_s: float = LONG_BOUNDARY_FSW_STEP_S,
    power_step_s: float = LONG_BOUNDARY_POWER_STEP_S,
) -> tuple[CampaignScenario, ...]:
    base = SelectiveUnifiedAssemblyConfig(
        duration_s=float(duration_s),
        dyn_step_s=float(dyn_step_s),
        fsw_step_s=float(fsw_step_s),
        power_step_s=float(power_step_s),
        sample_s=float(sample_s),
        # Long-horizon resource/boundary traces are not ADCS final-pointing
        # acceptance tests; avoid over-tight final attitude acceptance while
        # still recording attitude_error_ratio as a QoI.
        max_final_attitude_ratio=5.0,
    )
    zero_prop = (0.0, 0.0)
    return (
        CampaignScenario(
            "N0", "nominal_standby", "normal", "NOMINAL_STANDBY", "none",
            ("eps", "thermal", "adcs"), ("payload", "downlink", "propulsion"),
            replace(base, payload_power_w=0.0, instrument_baud_bps=0.0, comm_power_w=0.0, transmitter_baud_bps=0.0, payload_heat_w=2.0, propulsion_enabled=False, propulsion_on_time_s=zero_prop),
            "none",
        ),
        CampaignScenario(
            "N1", "nominal_observation", "normal", "NOMINAL_OBSERVATION", "none",
            ("eps", "payload", "thermal", "adcs", "comm_data_storage"), ("propulsion",),
            replace(base, payload_power_w=35.0, instrument_baud_bps=2.5e6, comm_power_w=0.0, transmitter_baud_bps=0.0, payload_heat_w=25.0, propulsion_enabled=False, propulsion_on_time_s=zero_prop),
            "none",
        ),
        CampaignScenario(
            "N2", "nominal_downlink", "normal", "NOMINAL_DOWNLINK", "none",
            ("eps", "comm_data", "adcs"), ("propulsion",),
            replace(base, payload_power_w=5.0, instrument_baud_bps=2.5e5, comm_power_w=22.0, transmitter_baud_bps=4.0e6, payload_heat_w=8.0, propulsion_enabled=False, propulsion_on_time_s=zero_prop),
            "none",
        ),
        CampaignScenario(
            "N3", "nominal_reboost_pulse", "normal", "NOMINAL_REBOOST", "none",
            ("eps", "adcs", "propulsion"), ("payload",),
            replace(base, payload_power_w=0.0, instrument_baud_bps=0.0, comm_power_w=0.0, transmitter_baud_bps=0.0, adcs_power_w=12.0, payload_heat_w=5.0, propulsion_enabled=True, propulsion_on_time_s=(0.1, 0.0, 0.0, 0.0)),
            "none",
        ),
        CampaignScenario(
            "B1", "low_soc_load_shedding", "normal_boundary", "NOMINAL_CHARGE_RECOVERY", "low_soc",
            ("eps", "adcs"), ("payload", "comm"),
            replace(base, initial_soc=0.35, solar_power_w=20.0, payload_power_w=35.0, comm_power_w=20.0, heater_power_w=6.0, propulsion_enabled=False, propulsion_on_time_s=zero_prop),
            "load_shed_active",
        ),
        CampaignScenario(
            "B2", "thermal_hot_boundary", "normal_boundary", "THERMAL_POWER_LOAD_MANAGEMENT", "thermal_hot",
            ("eps", "thermal", "adcs"), ("payload_if_thermal_unsafe",),
            replace(base, initial_temp_c=44.0, ambient_temp_c=35.0, payload_heat_w=120.0, payload_power_w=25.0, propulsion_enabled=False, propulsion_on_time_s=zero_prop),
            "thermal_margin_low_or_unsafe",
        ),
        CampaignScenario(
            "B3", "attitude_transient_boundary", "normal_boundary", "NOMINAL_OBSERVATION", "attitude_transient",
            ("adcs", "eps", "payload_after_ready"), (),
            replace(base, propulsion_enabled=False, propulsion_on_time_s=zero_prop),
            "attitude_transient_peak",
        ),
        CampaignScenario(
            "B4", "no_access_downlink_request", "normal_boundary", "NOMINAL_DOWNLINK", "no_ground_access_proxy",
            ("eps", "comm_data_storage", "adcs"), ("downlink_without_access",),
            replace(base, instrument_baud_bps=1.0e6, comm_power_w=10.0, transmitter_baud_bps=0.0, propulsion_enabled=False, propulsion_on_time_s=zero_prop),
            "no_access_downlink_blocked",
        ),
    )


def _finite(value: float) -> bool:
    return math.isfinite(float(value))


def _payload_block_reason(row: SelectiveUnifiedAssemblyTraceRow, scenario: CampaignScenario) -> str:
    if row.payload_load_enabled_w > 0:
        return "none"
    if row.load_shed_active and "payload" in row.shed_reason:
        return "pdu_load_shedding"
    if not row.thermal_safe or row.thermal_margin_c < 0:
        return "thermal_boundary"
    if scenario.name == "nominal_standby":
        return "not_requested"
    if scenario.name == "no_access_downlink_request":
        return "not_relevant"
    return "not_enabled"


def _to_unified_trace_row(scenario: CampaignScenario, row: SelectiveUnifiedAssemblyTraceRow, initial_fuel: float, initial_attitude_error: float) -> dict[str, object]:
    # The current selective unified assembly has no native ground access module in the campaign path.
    # For B4, access is intentionally represented as a zero-link-rate access proxy and labeled as
    # a normal-boundary case, not as a Basilisk groundLocation validation claim.
    ground_access = scenario.name != "no_access_downlink_request"
    sample_s = float(scenario.config.sample_s)
    generated_bits = max(0.0, float(row.instrument_baud_bps)) * sample_s
    link_rate = 0.0 if not ground_access else max(0.0, float(row.transmitter_baud_bps))
    downlinked_bits = link_rate * sample_s
    att_ratio = float(row.attitude_error_norm) / max(float(initial_attitude_error), 1e-12)
    thruster_on = bool(float(row.thrust_factor) > 0.0 or abs(float(row.thrust_force_n)) > 0.0)
    propellant_used = max(0.0, float(initial_fuel) - float(row.fuel_mass_kg))
    return {
        "scenario_id": scenario.scenario_id,
        "scenario_name": scenario.name,
        "scenario_type": scenario.scenario_type,
        "mode": scenario.mode,
        "time_s": float(row.time_s),
        "soc": float(row.battery_soc),
        "battery_storage_j": float(row.battery_storage_j),
        "solar_power_w": float(row.solar_power_w),
        "bus_load_w": float(row.bus_load_w),
        "payload_load_enabled_w": float(row.payload_load_enabled_w),
        "adcs_load_enabled_w": float(row.adcs_load_enabled_w),
        "comm_load_enabled_w": float(row.comm_load_enabled_w),
        "heater_load_enabled_w": float(row.heater_load_enabled_w),
        "load_shed_active": bool(row.load_shed_active),
        "shed_reason": str(row.shed_reason),
        "payload_enabled": bool(row.payload_load_enabled_w > 0.0),
        "payload_block_reason": _payload_block_reason(row, scenario),
        "data_storage_bits": float(row.data_storage_bits),
        "generated_bits": float(generated_bits),
        "downlinked_bits": float(downlinked_bits),
        "ground_access": bool(ground_access),
        "link_rate_bps": float(link_rate),
        "thermal_temp_c": float(row.thermal_temp_c),
        "thermal_safe": bool(row.thermal_safe),
        "heater_enabled": bool(row.heater_load_enabled_w > 0.0),
        "cooling_enabled": bool(row.thermal_margin_c < 5.0),
        "thermal_margin_c": float(row.thermal_margin_c),
        "attitude_error_norm": float(row.attitude_error_norm),
        "attitude_error_ratio": float(att_ratio),
        "rw_speed_0_rad_s": float(row.rw_speed_0_rad_s),
        "rw_speed_1_rad_s": float(row.rw_speed_1_rad_s),
        "rw_speed_2_rad_s": float(row.rw_speed_2_rad_s),
        # v8.25.2: renamed from rw_speed_sum_proxy to rw_speed_sum_nms
        "rw_speed_sum_nms": float(abs(row.rw_speed_0_rad_s) + abs(row.rw_speed_1_rad_s) + abs(row.rw_speed_2_rad_s)),
        # v8.25.2: renamed fields to clarify these are COMMAND values, not measured torque
        "rw_motor_torque_command_0_nm": float(getattr(row, "rw_motor_torque_command_0_nm", 0.0)),
        "rw_motor_torque_command_1_nm": float(getattr(row, "rw_motor_torque_command_1_nm", 0.0)),
        "rw_motor_torque_command_2_nm": float(getattr(row, "rw_motor_torque_command_2_nm", 0.0)),
        "rw_motor_torque_command_norm_nm": float(math.sqrt(
            float(getattr(row, "rw_motor_torque_command_0_nm", 0.0)) ** 2
            + float(getattr(row, "rw_motor_torque_command_1_nm", 0.0)) ** 2
            + float(getattr(row, "rw_motor_torque_command_2_nm", 0.0)) ** 2
        )),
        "sensor_quality_flag": "nominal" if row.estimator_quality >= 0.8 else "degraded",
        "nav_innovation_norm": float(row.nav_innovation_norm),
        "thruster_on": bool(thruster_on),
        "thruster_on_time_s": float(scenario.config.propulsion_config.thruster_command.nominal_on_time_s if thruster_on else 0.0),
        "fuel_mass_kg": float(row.fuel_mass_kg),
        "propellant_used_kg": float(propellant_used),
        "delta_v_proxy": float(row.velocity_x_m_s),
    }


def _boundary_events(scenario: CampaignScenario, trace_rows: list[dict[str, object]]) -> list[BoundaryEventLabel]:
    events: list[BoundaryEventLabel] = []
    if scenario.scenario_type != "normal_boundary":
        return events
    # Keep labels sparse: first occurrence for each event type is enough for dataset labels.
    seen: set[str] = set()
    for row in trace_rows:
        t = float(row["time_s"])
        if bool(row["load_shed_active"]) and "load_shedding" not in seen:
            seen.add("load_shedding")
            events.append(BoundaryEventLabel(scenario.scenario_id, t, "load_shedding", "normal_boundary", "eps_pdu", str(row["shed_reason"]), False))
        if float(row["thermal_margin_c"]) < 5.0 and "thermal_margin_low" not in seen:
            seen.add("thermal_margin_low")
            events.append(BoundaryEventLabel(scenario.scenario_id, t, "thermal_margin_low", "normal_boundary", "thermal", "thermal margin below 5 C", False))
        if float(row["attitude_error_ratio"]) > 1.0 and "attitude_transient" not in seen:
            seen.add("attitude_transient")
            events.append(BoundaryEventLabel(scenario.scenario_id, t, "attitude_transient", "normal_boundary", "adcs", "transient attitude error peak above initial error", False))
        if not bool(row["ground_access"]) and float(row["link_rate_bps"]) == 0.0 and "no_access_downlink_blocked" not in seen:
            seen.add("no_access_downlink_blocked")
            events.append(BoundaryEventLabel(scenario.scenario_id, t, "no_access_downlink_blocked", "normal_boundary", "comm_data", "downlink request with no access proxy produces zero link rate", False))
    return events


def _summarize(scenario: CampaignScenario, rows: list[dict[str, object]], events: list[BoundaryEventLabel]) -> ScenarioQoISummary:
    if not rows:
        return ScenarioQoISummary(scenario.scenario_id, scenario.name, scenario.scenario_type, "FAIL", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1)
    soc = [float(r["soc"]) for r in rows]
    data = [float(r["data_storage_bits"]) for r in rows]
    margin = [float(r["thermal_margin_c"]) for r in rows]
    att = [float(r["attitude_error_ratio"]) for r in rows]
    fuel = [float(r["propellant_used_kg"]) for r in rows]
    dv = [abs(float(r["delta_v_proxy"])) for r in rows]
    fail_count = 0
    warning_count = 0
    for r in rows:
        vals = [float(r[k]) for k in ("soc", "fuel_mass_kg", "data_storage_bits", "thermal_temp_c", "attitude_error_norm")]
        if any((not _finite(v)) for v in vals) or float(r["soc"]) < -1e-6 or float(r["fuel_mass_kg"]) < -1e-9 or float(r["data_storage_bits"]) < -1e-6:
            fail_count += 1
    if scenario.scenario_id == "B1" and not any(bool(r["load_shed_active"]) for r in rows):
        fail_count += 1
    if scenario.scenario_id == "B2" and not events:
        warning_count += 1
    if scenario.scenario_id == "B4" and any(float(r["link_rate_bps"]) > 0 for r in rows):
        fail_count += 1
    if max(att) > 2.0:
        warning_count += 1
    status = "PASS" if fail_count == 0 else "FAIL"
    return ScenarioQoISummary(
        scenario.scenario_id, scenario.name, scenario.scenario_type, status, len(rows),
        final_soc=soc[-1], min_soc=min(soc), final_data_storage_bits=data[-1], max_data_storage_bits=max(data),
        min_thermal_margin_c=min(margin), max_attitude_error_ratio=max(att), final_attitude_error_ratio=att[-1],
        propellant_used_kg=fuel[-1], max_velocity_x_m_s=max(dv), boundary_event_count=len(events), warning_count=warning_count, fail_count=fail_count,
    )


def run_selective_unified_normal_boundary_campaign(
    duration_s: float = LONG_BOUNDARY_DURATION_S,
    sample_s: float = LONG_BOUNDARY_SAMPLE_S,
    dyn_step_s: float = LONG_BOUNDARY_DYN_STEP_S,
    fsw_step_s: float = LONG_BOUNDARY_FSW_STEP_S,
    power_step_s: float = LONG_BOUNDARY_POWER_STEP_S,
) -> tuple[list[ScenarioQoISummary], list[dict[str, object]], list[ScenarioLabel], list[BoundaryEventLabel]]:
    all_rows: list[dict[str, object]] = []
    labels: list[ScenarioLabel] = []
    events: list[BoundaryEventLabel] = []
    summaries: list[ScenarioQoISummary] = []
    for scenario in _scenario_configs(duration_s=duration_s, sample_s=sample_s, dyn_step_s=dyn_step_s, fsw_step_s=fsw_step_s, power_step_s=power_step_s):
        summary, rows = run_selective_unified_assembly(scenario.config)
        if summary.status != "PASS":
            raise RuntimeError(f"scenario {scenario.scenario_id} underlying assembly failed: {summary.status}")
        initial_fuel = rows[0].fuel_mass_kg if rows else 0.0
        initial_att = rows[0].attitude_error_norm if rows else 0.0
        unified_rows = [_to_unified_trace_row(scenario, row, initial_fuel, initial_att) for row in rows]
        scenario_events = _boundary_events(scenario, unified_rows)
        all_rows.extend(unified_rows)
        events.extend(scenario_events)
        labels.append(ScenarioLabel(
            scenario.scenario_id, scenario.name, scenario.scenario_type, "none", scenario.boundary_type,
            ";".join(scenario.expected_active_subsystems), ";".join(scenario.expected_blocked_subsystems), False,
        ))
        summaries.append(_summarize(scenario, unified_rows, scenario_events))
    return summaries, all_rows, labels, events


def _write_csv(path: Path, rows: Iterable[object], fieldnames: list[str] | tuple[str, ...] | None = None) -> None:
    rows = list(rows)
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        if not rows:
            fieldnames = []
        elif isinstance(rows[0], dict):
            fieldnames = list(rows[0].keys())
        else:
            fieldnames = list(rows[0].__dataclass_fields__.keys())
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(fieldnames))
        writer.writeheader()
        for row in rows:
            writer.writerow(row if isinstance(row, dict) else asdict(row))


def write_selective_unified_normal_boundary_campaign(
    output_dir: str | Path = "datasets/selective_unified_normal_boundary_campaign",
    duration_s: float = LONG_BOUNDARY_DURATION_S,
    sample_s: float = LONG_BOUNDARY_SAMPLE_S,
    dyn_step_s: float = LONG_BOUNDARY_DYN_STEP_S,
    fsw_step_s: float = LONG_BOUNDARY_FSW_STEP_S,
    power_step_s: float = LONG_BOUNDARY_POWER_STEP_S,
) -> dict[str, str]:
    root = Path(output_dir)
    traces = root / "traces"
    labels_dir = root / "labels"
    summaries_dir = root / "summaries"
    manifests_dir = root / "manifests"
    for d in (traces, labels_dir, summaries_dir, manifests_dir):
        d.mkdir(parents=True, exist_ok=True)

    summaries, all_rows, labels, events = run_selective_unified_normal_boundary_campaign(duration_s=duration_s, sample_s=sample_s, dyn_step_s=dyn_step_s, fsw_step_s=fsw_step_s, power_step_s=power_step_s)
    # Per-scenario traces plus all-trace table.
    for label in labels:
        sid_rows = [r for r in all_rows if r["scenario_id"] == label.scenario_id]
        _write_csv(traces / f"{label.scenario_id}_{label.scenario_name}.csv", sid_rows, UNIFIED_TRACE_FIELDS)
    _write_csv(traces / "all_scenarios_trace.csv", all_rows, UNIFIED_TRACE_FIELDS)
    _write_csv(labels_dir / "scenario_labels.csv", labels)
    _write_csv(labels_dir / "boundary_event_labels.csv", events)
    _write_csv(summaries_dir / "qoi_summary.csv", summaries)

    pass_count = sum(1 for s in summaries if s.status == "PASS")
    fail_count = sum(1 for s in summaries if s.status == "FAIL")
    campaign_summary = {
        "dataset_type": "selective_unified_basilisk_normal_boundary_campaign_v8_25_1_long_horizon",
        "backend_truth": "all scenarios use the v8.22 selective unified Basilisk assembly path through SimulationBaseClass.ExecuteSimulation",
        "scenario_count": len(summaries),
        "pass_count": pass_count,
        "fail_count": fail_count,
        "normal_count": sum(1 for s in summaries if s.scenario_type == "normal"),
        "normal_boundary_count": sum(1 for s in summaries if s.scenario_type == "normal_boundary"),
        "boundary_event_count": len(events),
        "duration_s": float(duration_s),
        "duration_h": float(duration_s) / 3600.0,
        "sample_s": float(sample_s),
        "dyn_step_s": float(dyn_step_s),
        "fsw_step_s": float(fsw_step_s),
        "power_step_s": float(power_step_s),
        "min_long_boundary_duration_s": MIN_LONG_BOUNDARY_DURATION_S,
        "long_horizon_status": "PASS" if float(duration_s) >= MIN_LONG_BOUNDARY_DURATION_S else "FAIL",
        "status": "PASS" if fail_count == 0 and pass_count == len(summaries) else "FAIL",
        "not_claimed": [
            "fault_dataset",
            "complex_state_full_permutation",
            "formal_acceptance",
            "external_validation",
            "native_basilisk_thermal_network",
            "continuous_true_24h_orbit_propagation",
        ],
    }
    (summaries_dir / "campaign_summary.json").write_text(json.dumps(campaign_summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    manifest = {
        "dataset_type": campaign_summary["dataset_type"],
        "files": {
            "all_trace": "traces/all_scenarios_trace.csv",
            "scenario_labels": "labels/scenario_labels.csv",
            "boundary_event_labels": "labels/boundary_event_labels.csv",
            "qoi_summary": "summaries/qoi_summary.csv",
            "campaign_summary": "summaries/campaign_summary.json",
        },
        "schema_fields": list(UNIFIED_TRACE_FIELDS),
        "campaign_summary": campaign_summary,
    }
    (manifests_dir / "dataset_manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return {"root": str(root), "manifest": str(manifests_dir / "dataset_manifest.json"), "campaign_summary": str(summaries_dir / "campaign_summary.json")}


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default="datasets/selective_unified_normal_boundary_campaign")
    parser.add_argument("--duration-s", type=float, default=LONG_BOUNDARY_DURATION_S)
    parser.add_argument("--sample-s", type=float, default=LONG_BOUNDARY_SAMPLE_S)
    parser.add_argument("--dyn-step-s", type=float, default=LONG_BOUNDARY_DYN_STEP_S)
    parser.add_argument("--fsw-step-s", type=float, default=LONG_BOUNDARY_FSW_STEP_S)
    parser.add_argument("--power-step-s", type=float, default=LONG_BOUNDARY_POWER_STEP_S)
    args = parser.parse_args()
    print(json.dumps(write_selective_unified_normal_boundary_campaign(
        args.output_dir,
        duration_s=args.duration_s,
        sample_s=args.sample_s,
        dyn_step_s=args.dyn_step_s,
        fsw_step_s=args.fsw_step_s,
        power_step_s=args.power_step_s,
    ), indent=2, ensure_ascii=False))
